PISTE_SANDBOX_OAUTH_URL = "https://sandbox-oauth.piste.gouv.fr/api/oauth/token"
PISTE_OAUTH_URL = "https://oauth.piste.gouv.fr/api/oauth/token"
PISTE_CLIENT_ID = "<PISTE_CLIENT_ID>"
PISTE_CLIENT_SECRET = "<PISTE_CLIENT_SECRET>"

CHORUS_PRO_FACTURES_BASE_URL = "https://api.piste.gouv.fr/cpro"
CHORUS_PRO_SANDBOX_FACTURES_BASE_URL = "https://sandbox-api.piste.gouv.fr/cpro"

CHORUS_PRO_LOGIN = "<LOGIN>"
CHORUS_PRO_PASSWORD = "<PASSWORD>"

SAGE_BASE_URL = ""
SAGE_SANDBOX_BASE_URL = ""
SAGE_CLIENT_ID = "<SAGE_CLIENT_ID>"
SAGE_CLIENT_SECRET = "<SAGE_CLIENT_SECRET>"

PENNYLANE_API_VERSION = "/v1"
PENNYLANE_BASE_URL = "https://app.pennylane.com/api/external"
PENNYLANE_SANDBOX_BASE_URL = "<PENNYLANE_BASE_URL>"
PENNYLANE_CLIENT_ID = "<PENNYLANE_CLIENT_ID>"
PENNYLANE_CLIENT_SECRET = "<PENNYLANE_CLIENT_SECRET>"
